[toolchain]
anchor_version = "0.27.0"

[workspace]
members = ["programs/tax_reward"]

# Uncomment and set your deployed program ID and upgrade authority after first deploy:
[programs.localnet]
solana_tax_reward = "2A1sUwgtyMHswvfY2N4UTZLyPKLNjEHmhRzYFZgQgHQF"
upgrade_authority = "2A1sUwgtyMHswvfY2N4UTZLyPKLNjEHmhRzYFZgQgHQF"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test --skip-deploy"