# Prometheus configuration for Solana Tax & Reward monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'solana-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'dapp'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'batch-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:4000']